In [79]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score, classification_report, accuracy_score
%matplotlib inline

In [73]:
df = pd.read_csv(r'D:\SIC Batch 5\Tech Assignment #2\ai4i2020.csv')

df.head()

,UDI,Product ID,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure,TWF,HDF,PWF,OSF,RNF
0,1,M14860,M,298.1,308.6,1551,42.8,0,0,0,0,0,0,0
1,2,L47181,L,298.2,308.7,1408,46.3,3,0,0,0,0,0,0
2,3,L47182,L,298.1,308.5,1498,49.4,5,0,0,0,0,0,0
3,4,L47183,L,298.2,308.6,1433,39.5,7,0,0,0,0,0,0
4,5,L47184,L,298.2,308.7,1408,40.0,9,0,0,0,0,0,0

,Type,Air temperature [K],Process temperature [K],Rotational speed [rpm],Torque [Nm],Tool wear [min],Machine failure
0,M,298.1,308.6,1551,42.8,0,0
1,L,298.2,308.7,1408,46.3,3,0
2,L,298.1,308.5,1498,49.4,5,0
3,L,298.2,308.6,1433,39.5,7,0
4,L,298.2,308.7,1408,40.0,9,0
...,...,...,...,...,...,...,...
9995,M,298.8,308.4,1604,29.5,14,0
9996,H,298.9,308.4,1632,31.8,17,0
9997,M,299.0,308.6,1645,33.4,22,0
9998,H,299.0,308.7,1408,48.5,25,0
9999,M,299.0,308.7,1500,40.2,30,0

In [68]:
df.columns

Index(['UDI', 'Product ID', 'Type', 'Air temperature [K]',
       'Process temperature [K]', 'Rotational speed [rpm]', 'Torque [Nm]',
       'Tool wear [min]', 'Machine failure', 'TWF', 'HDF', 'PWF', 'OSF',
       'RNF'],
      dtype='object')

In [74]:
df.isnull().sum()

df.drop(['UDI', 'TWF', 'HDF', 'PWF', 'OSF', 'RNF'], axis=1)

x = df.drop('Machine failure', axis=1)
y = df['Machine failure']


x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [80]:
model_LR = LinearRegression()

model_LR.fit(x_train, y_train)

C:\Users\Theo Samuel\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_base.py:597: UserWarning: Skipping features without any observed values: ['Type']. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(

ValueError: Shape of passed values is (8000, 5), indices imply (8000, 6)

In [51]:
y_pred = model_LR.predict(x_test)

threshold = 0.5
y_pred_binary = (y_pred >= threshold).astype(int)

mse = mean_squared_error(y_test, y_pred)
print(f'Mean squared error : {mse}')

mae = mean_absolute_error(y_test, y_pred)
print(f'Mean Absolute Error: {mae}')

# R-squared (R2 Score)
r2 = r2_score(y_test, y_pred)
print(f'R-squared: {r2}')

accurate = accuracy_score(y_test, y_pred_binary)
print(f'Accuracy Score : ')
print(accurate)

class_rpt = classification_report(y_test, y_pred_binary)
print(f'Classification Report : ')
print(class_rpt)

Mean squared error : 0.003250981991771357
Mean Absolute Error: 0.010101233762541892
R-squared: 0.8900571701900978
Accuracy Score :
0.999
Classification Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1939
           1       1.00      0.97      0.98        61

    accuracy                           1.00      2000
   macro avg       1.00      0.98      0.99      2000
weighted avg       1.00      1.00      1.00      2000